// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE 'Core measures'[Distinc Students] = 
	CALCULATE(
     DISTINCTCOUNT ( FactPrograms[person_pk] ),
     FactPrograms[DaysBetween] > 4 )

EVALUATE
	SUMMARIZECOLUMNS(
		"New Measure", [Distinc Students]
	)